#!/usr/bin/php
<?php
$co_error = 0;

exec('git diff --cached --name-status --diff-filter=ACM', $output);
foreach ($output as $line) {
	$action = trim($line[0]);
	$fileName = trim(substr($line, 1));

	if(checkSyntax($fileName)) {
		$co_error = 300;
		$ds_return ='Erro de sintaxe';
		$error_message = "Arquivo: $fileName\n";
		$error_message .= "Erro de sintaxe em $fileName";
	}

	if(hasBannedFunction($fileName)) {
		$co_error = 400;
		$ds_return ='Funcao Banida';
		$error_message = "Arquivo: $fileName\n";
		$error_message.= "Tem uma funcao banida. Remova a funcao antes de continuar. Funcoes banidas; dump, die";
	}
}
if ($co_error != 0) {
	fwrite(STDERR, "------- \n");
	fwrite(STDERR, utf8_encode(" **** Erro $co_error: $ds_return **** \n"));
	fwrite(STDERR, utf8_encode(" **** ".fortuneCookie()." **** \n"));
	if ($error_message != "") {
		$error_message=explode("\n",$error_message);
		foreach ($error_message as $message) {
			fwrite(STDERR, utf8_encode(" **** $message **** \n"));
		}
	}
	fwrite(STDERR, "------- \n");
	exit(1);
}

exit(0);

function checkSyntax($fileName)
{
	$failed = false;
	
	if(preg_match('#\.php$#', $fileName)) {
		exec('cat ' . $fileName . ' | /usr/bin/php -l 2>/dev/null', $output, $failed);
	}

	return $failed;
}

/**
 * Recebe transacao e repositorio
 * Impede o commit se houver alguma funcao banida dentro do codigo php
 * @param string $txn - id da transacao
 * @param string $repos - path do repositorio
 */
function hasBannedFunction($fileName)
{
	exec('cat ' . $fileName, $output);
	$conteudo_php = implode("\n", $output);
	return preg_match('/(dump|die)\(/i', $conteudo_php);
}

function fortuneCookie() {
	$cookiejar = array(
			'Teje repreendido!',
			'Commit bloqueado por excesso de empadadas.',
			'YOU SHALL NOT... PASS!',
			'Trabalha direito senao o svn te denuncia',
			'Ah se num fosse esse pre-commit hein?',
			'Mais umas dessas e te passam pra o setor de design. (Se voce for um designer, ignore esse erro)',
			'Acorda!! Bebeu foi?',
			'Servidor blindado anti-caiada.',
			'No cookie for you mister.',
			'Errado.. de novo.',
			'Nem a pau que eu deixo uma coisa feia dessa passar.',
			'Bora cidadao, tenta de novo.',
			'Tem que ajeitar isso. Ta pronto?',
			'Ei bicho!? Ta empadando?'
	);
	$cookienumber = mt_rand(0,sizeof($cookiejar)-1);
	return $cookiejar[$cookienumber];
}